image: "python:3.9"

before_script:
    - cd ICD0004\ -\ Course\ Project/
    - pip3 install pipenv
    - pipenv install
    
stages:
    - test

test:
  stage: test  
  script:    
    - pipenv run python3 -m unittest discover --verbose
    
    
